basic/urls.py
from django.urls import path
from . import views

app_name = "basic"
urlpatterns = [
    path('', views.index, name='index'),

    path('<int:quiz_id>/', views.quizdetailview, name='quiz_detail'),

    path('take_quiz/<int:quiz_id>/', views.takequizview, name='take_quiz'),
    path('load_quiz_data/<int:quiz_id>/', views.load_quizdata_json, name='load_quiz_data'),
    path('results/<int:quiz_id>/', views.resultsview, name='results'),

    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

rook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('basic.urls')),
    path('admin/', admin.site.urls),
]

basic/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User, AbstractUser


class User(AbstractUser):
    score = models.IntegerField(default=0)
    attempts = models.IntegerField(default=0)
    # Other fields as needed (e.g., profile picture, bio)

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    instructions = models.TextField(blank=True, null=True)
    
    difficulty_level = models.CharField(max_length=20, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium')  
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,null=True, blank=True)
    time_limit = models.IntegerField(default=10)  # in minutes

    def __str__(self) -> str:
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    difficulty_level = models.CharField(max_length=20, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium')
    time_limit = models.IntegerField(default=30)  # in seconds
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self) -> str:
        if self.is_correct:
            return self.choice_text + " Correct"
        else:
            return self.choice_text
    

class UserAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True, blank=True)  # For multiple choice
    answer_text = models.TextField(blank=True, null=True)  # For other question types
    is_correct = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    started = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.answer_text


# class Score(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
#     score = models.IntegerField()
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self) -> str:
#         return f"{self.user.username} has score: {self.score}"

basic/views.py
from typing import Any
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import JsonResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse


from .models import Quiz, Choice, User

# Create your views here.
def index(request):
    quizlist = Quiz.objects.order_by('-created_at')[:10]
    return render(request, 'basic/index.html', {
        'list_of_quiz': quizlist
    })


def quizlistview(request):
    pass


# Quiz Detail: Show specific details of a quiz, including questions and options.
@login_required
def quizdetailview(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    all_questions = quiz.question_set.all()
    num_ques = len(all_questions)
    return render(request, 'basic/quiz_detail.html', {
        'quiz': quiz,
        'num_ques': num_ques,
    })


# Take Quiz: Allow users to attempt a quiz and submit answers.
@login_required
def takequizview(request, quiz_id):
    if request.method == 'GET':
        # load the quiz if it exists
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        questions = quiz.question_set.all()
        return render(request, 'basic/take_quiz.html', {
            'quiz': quiz,
            'questions': questions,
        })

           

def load_quizdata_json(request, quiz_id):
    if request.method == 'GET':
        # load the quiz if it exists
        quiz = get_object_or_404(Quiz, pk=quiz_id)

        # Prepare quiz and question data for JSON serialization
        quiz_data = {
            'id': quiz.id,
            'title': quiz.title,
        }

        questions_data = [
            {
                'id': question.id,
                'text': question.question_text,
                'time_limit': question.time_limit,

                'options': [
                    {'id': option.id, 'text': option.choice_text, 'is_correct': option.is_correct}
                    for option in question.choice_set.all()
                ]
            }
            for question in quiz.question_set.all()
        ]

        return JsonResponse({
            'quiz': quiz_data,
            'questions': questions_data,
        })

# Results: Display quiz results and scores.
def resultsview(request, quiz_id):
    if request.method == 'POST':
  

        score = 0
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        all_questions = quiz.question_set.all()
        num_questions = all_questions.count()

        for question in all_questions:
            selected_choice = request.POST.get(f'option-{question.id}')
            try:
                choice = Choice.objects.get(pk=selected_choice, question=question, is_correct=True)
                if choice:
                    score += 1
            except Choice.DoesNotExist:
                pass

        user = request.user
        user.score += score
        user.attempts += 1
        user.save()
        
        percentage = (score / num_questions) * 100
        context = {
            'score': score,
            'total_questions': num_questions,
            'percentage': percentage
        }
        return render(request, 'basic/results.html', context)
    # else:



def login_view(req):
    if req.method == "POST":

        # Attempt to sign user in
        username = req.POST["username"]
        password = req.POST["password"]
        user = authenticate(req, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(req, user)
            return redirect('index')
        else:
            return render(req, "basic/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(req, "basic/login.html")


def logout_view(req):
    logout(req)
    return HttpResponseRedirect(reverse(login_view))


def register(req):
    if req.method == "POST":
        username = req.POST["username"]

        # Ensure password matches confirmation
        password = req.POST["password"]
        confirmation = req.POST["confirmation"]
        if password != confirmation:
            return render(req, "basic/register.html", {
                "message": "Passwords must match."
            })
        
        # Attempt to create new user
        try:
            user = User.objects.create_user(
                username=username, 
                password=password,
            )
            user.save()
        except IntegrityError:
            return render(req, "basic/register.html", {
                "message": "Username already taken."
            })
        login(req, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(req, "basic/register.html")

@login_required
def user_profile(request):
    user = request.user
    context = {'user': user}
    return render(request, 'basic/user_profile.html', context)

basic/templates/basic/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> {% endcomment %}
    <link rel="stylesheet" href="{% static 'basic/style.css' %}">
    <link rel="shortcut icon" href="{% static 'basic/favicon.ico' %}" type="image/x-icon">
    {% comment %} <link rel="shortcut icon" href="{% static 'favicon.ico' %}"> {% endcomment %}
</head>
<body>
    <div class='container'>    
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

basic/templates/basic/index.html
{% extends "basic/base.html" %}

{% block body %}
<h2>All Quizes</h2>
<div class='quiz-list'>
{% for quiz in list_of_quiz %}
<div class='quiz-details-container'>
    <a href="{% url 'basic:quiz_detail' quiz.id %}">
        <div class=''>
            <h2 class="quiz-title">{{quiz.title}}</h2>
            
            <div class='quiz-specification'>
                <small><span>
                    <p>
                        <strong>Updated:</strong> {{ quiz.created_at }} <br>
                        <strong>{{ quiz.category | title }}</strong> &middot;
                        <strong class='difficulty-level-{{ quiz.difficulty_level | first }}'>{{ quiz.difficulty_level | title | first }}</strong> &middot;
                        <strong>{{ quiz.time_limit }} min</strong> &middot;
                        <strong>{{ quiz.no_ques }} Q</strong>
                    </p>
                </span></small>
            </div>
        </div>
    </a>
    <a href="{% url 'basic:quiz_detail' quiz.id %}" class="take-quiz-btn">View</a>
    {% comment %} <button  href="{% url 'basic:quiz_detail' quiz.id %}">view more</button> {% endcomment %}
</div>
{% endfor %}
</div>

{% endblock %}

basic/templates/basic/login.html
{% extends 'basic/base.html' %}

{% block body %}

<div class="auto-margin">
    <form action="{% url 'basic:login' %}" method="post">
        {% csrf_token %}
        
        <div class="warning">
          <small class="form-text">{{ message }}</small>
        </div>

        <div class="form-group">
          <small class="form-text text-muted">Enter your username</small>
          <input type="text" class="form-control" name="username">
        </div>

        <div class="form-group">
          <small class="form-text text-muted">Enter your password</small>
          <input type="password" class="form-control" name="password">
          <!-- <a href="#">
            <small class="form-text text-muted">Forgot password?</small>
          </a> -->
        </div>
        
        <button type="submit" class="btn btn-link">Enter</button>
      </form>
</div>

{% endblock %}

basic/templates/basic/quiz_detail.html
{% extends 'basic/base.html' %}
{% load static %}

{% block title %}{{quiz.title}}{% endblock %}

{% block body %}
    <div class="quiz-details-container">
        <h1 class='quiz-title'>{{ quiz.title }}</h1>
        <p class='quiz-description'>{{ quiz.description }}</p>
        
        <div class='quiz-specification'>
        <small><span>
            <p>
                <strong>Updated:</strong> {{ quiz.created_at }} <br>
                <strong>{{ quiz.category | title }}</strong> &middot;
                <strong class='difficulty-level-{{ quiz.difficulty_level | first }}'>{{ quiz.difficulty_level | title | first }}</strong> &middot;
                <strong>{{ quiz.time_limit }} min</strong> &middot;
                <strong>{{ num_ques }} Q</strong>
            </p>
        </span></small>
    </div>

    <div id='take-quiz-btn-div'>
        <a href="{% url 'basic:take_quiz' quiz.id %}" class="take-quiz-btn">Take Quiz</a>
    </div>

{% endblock %}

basic/templates/basic/quiz_list.html
{% extends 'basic/base.html' %}

{% block title %}Quiz List{% endblock %}

{% block body %}
    <div class="quiz-list">
        {% for quiz in quizzes %}
            <a href="{% url 'basic:quiz_details' quiz.id %}" class="quiz-item">
                <h2 class="quiz-title">{{ quiz.title }}</h2>
                <p class="quiz-description">{{ quiz.description }}</p>
            </a>
        {% endfor %}
    </div>
{% endblock %}

basic/templates/basic/register.html
{% extends 'basic/base.html' %}

{% block body %}

<div class="auto-margin">
    <form action="{% url 'basic:register' %}" method="post">
        {% csrf_token %}

        <div class="warning">
          <small class="form-text">{{ message }}</small>
        </div>

        <div class="form-group">
          <small class="form-text text-muted">Pick a username</small>
          <input type="text" class="form-control" name="username">
        </div>

        <div class="form-group">
            <small class="form-text text-muted">Set password for your account</small>
            <input type="password" class="form-control" name="password">
            <div class="mb-1"></div>
            <small class="form-text text-muted">Enter the password again</small>
            <input type="password" class="form-control" name="confirmation">
        </div>
        
        <button type="submit" class="btn btn-link">Register</button>
      </form>
</div>

{% endblock %}

basic/templates/basic/results.html
{% extends "basic/base.html" %}

{% block body %}
<h1>Quiz Results</h1>
<p>You scored {{ score }} out of {{ total_questions }}</p>
<p>Your percentage is {{ percentage }}%</p>
{% endblock %}

basic/templates/basic/take_quiz.html
{% extends "basic/base.html" %}
{% load static %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block body %}

<div id='question-paper'>
    <div class='center-item'>
        <div class="progress-bar-container">
            <div id='progress-bar' class="progress-bar"></div>
        </div>

        <form action="{% url 'basic:results' quiz.id %}" method='post'>
            {% csrf_token %}
            
            {% for question in questions %}
            <p id='curr-question-text'>{{ question.question_text }}</p>
            {% for choice in question.choice_set.all %}
            <div>
                <input type="radio" id="option-{{ question.id }}" name="option-{{ question.id }}" value="{{ choice.id }}" />
                <label for="option-{{ question.id }}">{{ choice.choice_text }}</label>
            </div>
            {% endfor %}
            {% endfor %}

        <button type='submit' id='submit-quiz-btn' class="submit-quiz-btn">Submit</button>
        </form>
        
    </div>

    <div id='quit-quiz-btn-div'>
        <input type="hidden" id="quiz_id" value='{{ quiz.id }}'>
        {% comment %} <button id='quit-quiz-btn' class="quit-quiz-btn">Quit</button> {% endcomment %}
    </div>

</div>
<script src="{% static 'basic/logic.js' %}"></script>
{% endblock %}

basic/templates/basic/template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> {% endcomment %}
    <link rel="stylesheet" href="{% static 'basic/style.css' %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

basic/templates/basic/user_profile.html
{% extends "basic/base.html" %}

{% block body %}
<h1>{{ user.username }}</h1>
<p>{{ user.score }}</p>
{% endblock %}